# 动态调度代理配置示例

# 通用配置
common:
  log_level: "info"
  log_file: "dynamic-proxy.log"
  admin_addr: "127.0.0.1:8888"
  node_id: "proxy-node-1"
  region: "us-east"

# 监听器配置
listeners:
  - name: "web-listener"
    bind: "0.0.0.0:8080"
  - name: "api-listener"
    bind: "0.0.0.0:9090"

# 调度器配置
scheduler:
  address: "127.0.0.1:9999"
  connect_timeout: "30s"
  request_timeout: "10s"
  retry_interval: "5s"
  max_retries: 3
  heartbeat_interval: "30s"

# 对等节点配置（用于节点发现和通信）
peers:
  - name: "proxy-node-2"
    address: "192.168.1.50:9090"
    type: "tcp"
    region: "us-west"
  
  - name: "proxy-node-3"
    address: "192.168.1.51:9090"
    type: "tcp"
    region: "eu-central"
